# version: "3.9"

# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: ktor
#       POSTGRES_PASSWORD: ktor
#       POSTGRES_DB: ktor_db
#     ports:
#       - "5433:5432"   # host:container
#     volumes:
#       - db_data:/var/lib/postgresql/data

# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: todos
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:

version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ktor
      POSTGRES_PASSWORD: ktor
      POSTGRES_DB: ktor_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_JDBC_URL: "jdbc:postgresql://db:5432/ktor_db"
      DB_USER: "ktor"
      DB_PASS: "ktor"
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "./gradlew run"

volumes:
  db_data: